# Generated by Django 2.0 on 2018-05-31 12:00

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authtoken', '0002_auto_20160226_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomToken',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('authtoken.token',),
        ),
    ]
