# Generated by Django 2.0 on 2018-05-31 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from settings import create_superuser, SET_USER_START_ID


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('username', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='用户名')),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='手机号')),
                ('is_staff', models.BooleanField(default=False, verbose_name='职员状态')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('acct_type', models.CharField(choices=[('E', '显式注册'), ('I', '邀请注册'), ('O', '第3方登录注册')], default='E', max_length=2, verbose_name='账号类型')),
                ('avatar', models.CharField(blank=True, default='', max_length=80, null=True, verbose_name='头像')),
                ('nickname', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='昵称')),
                ('birth', models.DateField(auto_now_add=True, null=True, verbose_name='生日')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女'), ('U', '未知')], default='U', max_length=1, verbose_name='性别')),
                ('login_count', models.IntegerField(default=0, verbose_name='登录次数')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='最后登录IP')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'users_user',
                'swappable': 'AUTH_USER_MODEL',
            },
        ),
        migrations.CreateModel(
            name='ResetRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('key', models.CharField(max_length=128)),
                ('expire_datetime', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),

        # ############################# added by junn   #############################
        migrations.RunSQL(  # id自增从设定的值开始
            SET_USER_START_ID,
        ),

        migrations.RunPython(create_superuser),  # create superuser for sys_admin
    ]
